// Collects every CJK glyph used in src/ so the kanji web font can be subset to exactly those
// (a few KB instead of megabytes). Runs before `next build`; the output is committed too.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const chars = new Set();
const walk = (d) => {
  for (const f of readdirSync(d)) {
    const p = join(d, f);
    if (statSync(p).isDirectory()) walk(p);
    else if (/\.(ts|tsx)$/.test(f) && !p.endsWith("kanji.ts"))
      for (const ch of readFileSync(p, "utf8")) {
        const o = ch.codePointAt(0);
        if ((o >= 0x3000 && o <= 0x9fff) || (o >= 0xf900 && o <= 0xfaff)) chars.add(ch);
      }
  }
};
walk("src");
const s = [...chars].sort().join("");
writeFileSync("src/app/kanji.ts", `// Generated by scripts/kanji.mjs — every kanji/kana the game displays.\nexport const KANJI = ${JSON.stringify(s)};\n`);
console.log(`kanji subset: ${s.length} glyphs`);
